### ISSUE TITLE
Find out what extra pages we need

### ISSUE THREAD

**Issue by JohannaJoergensen** [jpmorganchase/uitk#616]
Need to find out if we need pages like Privacy Statement, etc.

**Comment by JohannaJoergensen** [comment]
23 Nov - research in progress, aim to get this done by EOD Thurs, 24 Nov

**Comment by james-nash** [comment]
In the first instance, we don't need to create additional pages of our own. However, our footer should include links to the following:

* "Privacy", which should link to https://www.jpmorgan.com/privacy
* "Terms of use", which should link to https://www.jpmorgan.com/terms
* "Cookies Policy", which should link to https://www.jpmorgan.com/cookies

I've also identified some other things to include in our page footer, but since that's beyond the scope of this issue, I'll raise a separate one for that
