### ISSUE TITLE
Site Nav Initial Planning & Implementation

### ISSUE THREAD

**Issue by EleanorHaproff** [jpmorganchase/uitk#622]
- [ ] Gather url requirements
- [ ] Decide & implement whether to use docs or pages for which sections
- [ ] Ensure urls are correct
- [ ] Ensure navigation styles are all correct e.g. active

See https://github.com/jpmorganchase/uitk/tree/site-nav-experiment

**Comment by JohannaJoergensen** [comment]
8 Nov - need to with James regarding how we want the URLs to look like

**Comment by JoanaMMoreira** [comment]
I've raised this draft PR: https://github.com/jpmorganchase/uitk/pull/638 
@james-nash it would be good to discuss when you're back

**Comment by james-nash** [comment]
> need to with James regarding how we want the URLs to look like

My preference would be to keep them fairly shallow. I'm thinking something like:

* Home: `/`
* Getting started: `/getting-started/`
* Components: `/components/`
* Contributing: `/contributing/`

Of course, if we rename any of those pages (I know the content team's not so keen on "contributing", so that may end up being called something else), then the URL path should change accordingly.

The key thing is, that we eliminate that `/docs/` prefix that Docusaurus adds out of the box from the URLs as I think it's redundant in our case (though we can still have the corresponding source MDX files under `src/docs/`, where it makes sense to do so). Based on my brief experimentation, it seems [you can do that in `docusaurus.config.js`](https://github.com/jpmorganchase/uitk/compare/main...site-nav-experiment#diff-c30c28b42f26a8fa3bfefdc56fabb99e519554fb3e878e56d060cf2fc1708a8dR34).

**Comment by JoanaMMoreira** [comment]
@james-nash could you please take a look at this PR: https://github.com/jpmorganchase/uitk/pull/638
